"""Pre-registered statistical tests for the explanation-agreement study.

The analysis plan (FIX_PLAN_2026-07-02.md §P1.3) pre-registers exactly two
hypothesis-test families, both permutation-based (no distributional assumptions
at pilot N), with Holm–Bonferroni correction within each family:

  1. Per model×dataset cell: mean ECS-lift > 0
     -> sign_flip_permutation_test over per-instance (ecs - ecs_random) values.
  2. Erasure pass, per model per operator: CC-erasure flip rate > random flip rate
     -> sign_flip_permutation_test over per-instance (cc_flip - random_rate)
        paired differences (pairing is within-instance, never across instances).

Everything else in the reports is descriptive. Anything beyond these two
families must be added to the plan BEFORE being run, not after seeing the data.

Also provided: Spearman correlation between verbalized confidence and ECS with a
seeded bootstrap CI (a pre-registered ASSOCIATION estimate, reported with its CI
rather than as a hypothesis test), and a generic two-sample permutation test for
exploratory use (label any use of it as exploratory).
"""
import numpy as np
import scipy.stats
from typing import List, Optional, Sequence, Tuple
from dataclasses import dataclass


@dataclass
class CorrelationResult:
    rho: float
    p_value: float
    ci_lower: float
    ci_upper: float
    n: int = 0


def compute_confidence_ecs_correlation(confidences: List[float], ecs_values: List[float],
                                        n_bootstrap: int = 1000,
                                        seed: Optional[int] = 42) -> CorrelationResult:
    """Spearman rho between verbalized confidence and ECS, with a seeded bootstrap CI.

    Requires paired inputs (confidences[i] and ecs_values[i] from the same instance).
    Returns a degenerate (0, 1) result below n=3 or when either input is constant.
    """
    n = min(len(confidences), len(ecs_values))
    if len(confidences) != len(ecs_values):
        # Paired estimate — silently truncating would pair unrelated instances.
        raise ValueError(
            f"compute_confidence_ecs_correlation requires paired equal-length inputs, "
            f"got {len(confidences)} vs {len(ecs_values)}"
        )
    if n < 3:
        return CorrelationResult(rho=0.0, p_value=1.0, ci_lower=0.0, ci_upper=0.0, n=n)
    rho, p_value = scipy.stats.spearmanr(confidences, ecs_values)
    if np.isnan(rho):
        return CorrelationResult(rho=0.0, p_value=1.0, ci_lower=0.0, ci_upper=0.0, n=n)
    rng = np.random.default_rng(seed)
    boot_rhos = []
    for _ in range(n_bootstrap):
        idx = rng.choice(n, n, replace=True)
        try:
            boot_rho, _ = scipy.stats.spearmanr([confidences[i] for i in idx], [ecs_values[i] for i in idx])
            if not np.isnan(boot_rho):
                boot_rhos.append(boot_rho)
        except Exception:
            continue
    ci_lower = float(np.percentile(boot_rhos, 2.5)) if boot_rhos else 0.0
    ci_upper = float(np.percentile(boot_rhos, 97.5)) if boot_rhos else 0.0
    return CorrelationResult(rho=float(rho), p_value=float(p_value),
                             ci_lower=ci_lower, ci_upper=ci_upper, n=n)


def sign_flip_permutation_test(diffs: Sequence[float], n_permutations: int = 10000,
                                seed: Optional[int] = 42,
                                alternative: str = "greater") -> Optional[float]:
    """One-sample sign-flip permutation test on paired differences.

    H0: the differences are symmetrically distributed around 0 (no effect).
    Under H0 each difference's sign is exchangeable, so the null distribution of
    the mean is generated by randomly flipping signs. This is the standard exact
    (up to Monte-Carlo error) paired test with no normality assumption — the
    correct instrument for per-instance paired quantities like (ecs - ecs_random)
    or (cc_flip - random_flip_rate).

    alternative: "greater" (mean > 0), "less", or "two-sided".
    Returns the p-value with the +1 correction (Phipson & Smyth 2010), or None
    when there are fewer than 2 non-null differences (a test at n<2 is noise).
    """
    xs = np.array([d for d in diffs if d is not None], dtype=float)
    if len(xs) < 2:
        return None
    observed = float(np.mean(xs))
    rng = np.random.default_rng(seed)
    signs = rng.choice([-1.0, 1.0], size=(n_permutations, len(xs)))
    perm_means = (signs * xs).mean(axis=1)
    if alternative == "greater":
        count = int(np.sum(perm_means >= observed))
    elif alternative == "less":
        count = int(np.sum(perm_means <= observed))
    elif alternative == "two-sided":
        count = int(np.sum(np.abs(perm_means) >= abs(observed)))
    else:
        raise ValueError(f"Unknown alternative: {alternative}")
    return (count + 1) / (n_permutations + 1)


def permutation_test(group1: List[float], group2: List[float], n_permutations: int = 10000,
                      seed: Optional[int] = None) -> float:
    """Two-sample (unpaired) permutation test on the difference of means.

    Exploratory only — the pre-registered paired comparisons use
    sign_flip_permutation_test. Kept for independent-group contrasts.
    """
    observed = abs(np.mean(group1) - np.mean(group2))
    combined = list(group1) + list(group2)
    n1 = len(group1)
    rng = np.random.default_rng(seed)
    count = 0
    for _ in range(n_permutations):
        rng.shuffle(combined)
        perm_mean1 = np.mean(combined[:n1])
        perm_mean2 = np.mean(combined[n1:])
        if abs(perm_mean1 - perm_mean2) >= observed:
            count += 1
    return (count + 1) / (n_permutations + 1)


def holm_correction(p_values: List[Optional[float]]) -> List[Optional[float]]:
    """Holm–Bonferroni step-down adjusted p-values.

    Uniformly more powerful than plain Bonferroni at the same FWER guarantee,
    with no independence assumption — the pre-registered correction for both
    test families. None entries (tests that could not run, e.g. n<2) are
    passed through untouched and do not count toward the family size.
    """
    indexed = [(i, p) for i, p in enumerate(p_values) if p is not None]
    m = len(indexed)
    adjusted: List[Optional[float]] = [None] * len(p_values)
    if m == 0:
        return adjusted
    indexed.sort(key=lambda x: x[1])
    running_max = 0.0
    for rank, (i, p) in enumerate(indexed):
        adj = min((m - rank) * p, 1.0)
        running_max = max(running_max, adj)  # enforce monotonicity
        adjusted[i] = running_max
    return adjusted


def are_significant(p_values: List[Optional[float]], corrected: bool = True,
                    alpha: float = 0.05) -> List[bool]:
    """Significance flags at level alpha, Holm-corrected by default.
    None p-values (test not run) are never significant."""
    ps = holm_correction(p_values) if corrected else p_values
    return [(p is not None and p <= alpha) for p in ps]
