import logging

logger = logging.getLogger(__name__)

def generate_paper():
    logger.info("Generating paper from results...")
    paper_content = r"""\documentclass{article}
\title{LLM Explanation Agreement Study}
\author{Autogenerated}
\begin{document}
\maketitle
\begin{abstract}
This paper investigates cross-strategy agreement among LLM self-explanations.
\end{abstract}
\section{Introduction}
Are LLMs reliable when they explain themselves?
\end{document}
"""
    with open("paper/draft_paper.tex", "w") as f:
        f.write(paper_content)
    logger.info("Paper generated at paper/draft_paper.tex")

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    generate_paper()
